GET http://localhost:3000/api/summary/registerSDCSDCS
Accept: application/json


### auth

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "test633@email.com",
  "password": "password",
  "name": "test"
}

### get summaries by user
GET http://localhost:3000/api/users/669b142721ec997e621b447e/summaries


### add delete summary by user id
GET http://localhost:3000/api/users/669b142721ec997e621b447e/summaries/sumariD

### add summary
POST http://localhost:3000/api/users/669b142721ec997e621b447e/summaries
Content-Type: application/json

{
  "summary":{
    "title": "II World War",
    "description": "The Second World War was the deadliest conflict in human history. It lasted from 1939 to 1945 and involved 30 countries from every part of the globe. World War II killed around 70 million people or 4% of the world's population. It was the most destructive war in history and caused the fall of four great empires: the British, French, German, and Japanese empires.",
    "content": "The war began on September 1, 1939, when Germany invaded Poland. Britain and France declared war on Germany two days later. The war in Europe ended on May 8, 1945, when Germany surrendered. The war in the Pacific ended on August 15, 1945, when Japan surrendered. The war ended with the unconditional surrender of the Axis powers. The war was fought on land, at sea, and in the air. It was fought in Europe, Asia, Africa, and the Pacific. The war was fought with tanks, ships, submarines, and airplanes. It was fought with rifles, machine guns, and artillery. It was fought with bombs, torpedoes, and rockets. It was fought with poison gas, flamethrowers, and nuclear weapons. The war was fought by soldiers, sailors, and airmen"
  }  
}

### delete summary by id of one user
DELETE http://localhost:3000/api/users/669b142721ec997e621b447e/summaries/669b184721ec997e621b448c


### manipulate summaries by id
GET http://localhost:3000/api/summary/669b184721ec997e621b448c


### maps by summary id
GET http://localhost:3000/api/summary/id-123345/maps