
export enum ROLES {
    VIP = 'VIP',
    USER = 'USER',
    GUEST = 'GUEST',
    ADMIN = 'ADMIN'
}

export enum MAP_TYPES {
    FLOWCHART = 'FLOWCHART',
    SEQUENCE = 'SEQUENCE',
    GANTT = 'GANTT',
    CLASS = 'CLASS',
    STATE = 'STATE',
    ENTITY = 'ENTITY',
    MINDMAP = 'MINDMAP',
}
export type ALLOWED_MAP_TYPES = (typeof MAP_TYPES)[keyof typeof MAP_TYPES];
export type ALLOWED_ROLES = (typeof ROLES)[keyof typeof ROLES];


// MAPMIND CANVAS PROVIDERS

export enum CANVAS_PROVIDERS {
    EXCALIDRAW = 'EXCALIDRAW',
    MERMAID = 'MERMAID',
}



export type ALLOWED_CANVAS_PROVIDERS = (typeof CANVAS_PROVIDERS)[keyof typeof CANVAS_PROVIDERS];

// MAPMIND LANGUAGES SUPPORTED
export enum LANGUAGES_CANVAS {
    MERMAID = 'MERMAID',
}

export type ALLOWED_LANGUAGES_CANVAS = (typeof LANGUAGES_CANVAS)[keyof typeof LANGUAGES_CANVAS];


// TYPE OF DIAGRAMS SUPPORTED BY CANVAS PROVIDERS

export type DIAGRAMS_SUPPORTED = {
    [CANVAS_PROVIDERS.EXCALIDRAW]: ALLOWED_MAP_TYPES[];
    [CANVAS_PROVIDERS.MERMAID]: ALLOWED_MAP_TYPES[];

};

export const DIAGRAMS_SUPPORTED_BY_CANVAS: DIAGRAMS_SUPPORTED = {
    [CANVAS_PROVIDERS.EXCALIDRAW]: [MAP_TYPES.FLOWCHART, MAP_TYPES.SEQUENCE, MAP_TYPES.GANTT, MAP_TYPES.CLASS, MAP_TYPES.STATE, MAP_TYPES.ENTITY,],
    [CANVAS_PROVIDERS.MERMAID]: [MAP_TYPES.FLOWCHART, MAP_TYPES.SEQUENCE, MAP_TYPES.GANTT, MAP_TYPES.CLASS, MAP_TYPES.STATE, MAP_TYPES.ENTITY, MAP_TYPES.MINDMAP],
};